idx: 450
erasor: 
    max_range: 60.0  # 20 / 15 also good     10/5 For Korea Univ!!
    num_rings: 15    # 35   # 0911_{3, 4} 는 20이었음
    num_sectors: 60 # 108
    min_h: -1.3
    max_h: 3.2
    th_bin_max_h: 0.05 # [m]
    scan_ratio_threshold: 0.3 # percentage: originally, 0.3 yet 0.3 seems like it is quite aggressive!
    minimum_num_pts: 10
    rejection_ratio: 0
    sac_distThr: 0.05
    gf_distThr: 0.15
    gf_iter: 3
    gf_num_lpr: 10
    gf_th_seeds_height: 0.5
    version: 3



MapUpdater:

    data_name: "05"
    initial_map_path: "/media/shapelim/UX960NVMe1/kitti_semantic/semantic_KITTI_map/src_0_2_test/05_2350_to_2670_w_interval1_voxel_0.200000.pcd"
    env: "outdoor"
    save_path: "/media/shapelim/UX960NVMe1/kitti_semantic/semantic_KITTI_map/src_0_2_test"
    query_voxel_size: 0.2
    map_voxel_size: 0.05 
    voxelization_interval: 5
    removal_interval: 8

tf:
     lidar2body: [0.0, 0.0, 1.73, 0, 0.0, 0.0, 1.0] # xyz q_x, q_y, q_z, q_w in order

verbose: true


